import { useState } from 'react';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { toast } from 'sonner';
import {
  Download,
  Share2,
  Copy,
  Check,
  FileText,
  Loader2,
  Link2,
} from 'lucide-react';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

interface RoadmapExportShareProps {
  roadmapId: string;
  targetSkill: string;
  roadmapData: any;
}

export default function RoadmapExportShare({ roadmapId, targetSkill, roadmapData }: RoadmapExportShareProps) {
  const [exporting, setExporting] = useState(false);
  const [copied, setCopied] = useState(false);
  const [shareDialogOpen, setShareDialogOpen] = useState(false);

  const shareUrl = `${window.location.origin}/roadmap/${roadmapId}`;

  const handleCopyLink = async () => {
    try {
      await navigator.clipboard.writeText(shareUrl);
      setCopied(true);
      toast.success('Link copied to clipboard!');
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      toast.error('Failed to copy link');
    }
  };

  const handleExportPDF = async () => {
    setExporting(true);
    try {
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const margin = 15;
      let yPos = margin;

      // Title
      pdf.setFontSize(24);
      pdf.setTextColor(59, 130, 246); // Primary blue
      pdf.text(targetSkill, margin, yPos);
      yPos += 12;

      pdf.setFontSize(12);
      pdf.setTextColor(107, 114, 128); // Gray
      pdf.text('Learning Roadmap', margin, yPos);
      yPos += 15;

      // Phases
      const phases = roadmapData.phases || [];
      
      phases.forEach((phase: any, phaseIndex: number) => {
        // Check if we need a new page
        if (yPos > pageHeight - 40) {
          pdf.addPage();
          yPos = margin;
        }

        // Phase header
        pdf.setFontSize(16);
        pdf.setTextColor(31, 41, 55);
        pdf.text(`Module ${phaseIndex + 1}: ${phase.name}`, margin, yPos);
        yPos += 8;

        if (phase.description) {
          pdf.setFontSize(10);
          pdf.setTextColor(107, 114, 128);
          const descLines = pdf.splitTextToSize(phase.description, pageWidth - 2 * margin);
          pdf.text(descLines, margin, yPos);
          yPos += descLines.length * 5 + 5;
        }

        // Skills
        phase.skills?.forEach((skill: any, skillIndex: number) => {
          if (yPos > pageHeight - 30) {
            pdf.addPage();
            yPos = margin;
          }

          pdf.setFontSize(12);
          pdf.setTextColor(55, 65, 81);
          const skillTitle = `${skillIndex + 1}. ${skill.name}`;
          pdf.text(skillTitle, margin + 5, yPos);
          yPos += 6;

          pdf.setFontSize(10);
          pdf.setTextColor(107, 114, 128);
          
          // Time estimate
          const timeText = skill.days || skill.estimatedTime || '';
          if (timeText) {
            pdf.text(`Duration: ${timeText}`, margin + 10, yPos);
            yPos += 5;
          }

          // Description
          if (skill.description) {
            const skillDescLines = pdf.splitTextToSize(skill.description, pageWidth - 2 * margin - 10);
            pdf.text(skillDescLines, margin + 10, yPos);
            yPos += skillDescLines.length * 4 + 3;
          }

          // Resources
          if (skill.resources && skill.resources.length > 0) {
            pdf.setFontSize(9);
            pdf.setTextColor(59, 130, 246);
            skill.resources.forEach((resource: string) => {
              if (yPos > pageHeight - 15) {
                pdf.addPage();
                yPos = margin;
              }
              const resourceText = resource.startsWith('http') 
                ? resource.substring(0, 60) + (resource.length > 60 ? '...' : '')
                : resource.substring(0, 70) + (resource.length > 70 ? '...' : '');
              pdf.text(`• ${resourceText}`, margin + 10, yPos);
              yPos += 4;
            });
          }

          yPos += 5;
        });

        yPos += 10;
      });

      // Footer
      pdf.setFontSize(8);
      pdf.setTextColor(156, 163, 175);
      pdf.text(`Generated by SkillPath • ${new Date().toLocaleDateString()}`, margin, pageHeight - 10);

      pdf.save(`${targetSkill.replace(/\s+/g, '-')}-roadmap.pdf`);
      toast.success('PDF exported successfully!');
    } catch (error) {
      console.error('PDF export error:', error);
      toast.error('Failed to export PDF');
    } finally {
      setExporting(false);
    }
  };

  return (
    <div className="flex items-center gap-3">
      {/* Export PDF Button */}
      <Button
        variant="outline"
        onClick={handleExportPDF}
        disabled={exporting}
        className="gap-2"
      >
        {exporting ? (
          <Loader2 className="w-4 h-4 animate-spin" />
        ) : (
          <Download className="w-4 h-4" />
        )}
        Export PDF
      </Button>

      {/* Share Dialog */}
      <Dialog open={shareDialogOpen} onOpenChange={setShareDialogOpen}>
        <DialogTrigger asChild>
          <Button variant="outline" className="gap-2">
            <Share2 className="w-4 h-4" />
            Share
          </Button>
        </DialogTrigger>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Link2 className="w-5 h-5 text-primary" />
              Share Roadmap
            </DialogTitle>
          </DialogHeader>
          <div className="space-y-4 mt-4">
            <p className="text-sm text-muted-foreground">
              Share your learning roadmap with others using this unique link:
            </p>
            <div className="flex gap-2">
              <Input
                value={shareUrl}
                readOnly
                className="bg-secondary/50"
              />
              <Button onClick={handleCopyLink} size="icon" variant="outline">
                {copied ? (
                  <Check className="w-4 h-4 text-success" />
                ) : (
                  <Copy className="w-4 h-4" />
                )}
              </Button>
            </div>
            <div className="pt-4 border-t border-border">
              <p className="text-xs text-muted-foreground">
                Note: Anyone with this link can view your roadmap (read-only).
              </p>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
